// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxdljxL7NyGmSXUrnZLv4hl_kJoLV9ok',
    appId: '1:1042575440295:web:503ffd59fa6f43c7e8de82',
    messagingSenderId: '1042575440295',
    projectId: 'rafe-3a961',
    authDomain: 'rafe-3a961.firebaseapp.com',
    databaseURL: 'https://rafe-3a961-default-rtdb.firebaseio.com',
    storageBucket: 'rafe-3a961.firebasestorage.app',
    measurementId: 'G-Z6Y003LD5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5fiOLbyGXEbxTagfPhNGIdBXzxZas2Ig',
    appId: '1:1042575440295:android:65a2ebac797d207de8de82',
    messagingSenderId: '1042575440295',
    projectId: 'rafe-3a961',
    databaseURL: 'https://rafe-3a961-default-rtdb.firebaseio.com',
    storageBucket: 'rafe-3a961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCab4NAC1L2tEdirexVUpFqOhQM3nyr5ag',
    appId: '1:1042575440295:ios:a4293e7effdcd4d3e8de82',
    messagingSenderId: '1042575440295',
    projectId: 'rafe-3a961',
    databaseURL: 'https://rafe-3a961-default-rtdb.firebaseio.com',
    storageBucket: 'rafe-3a961.firebasestorage.app',
    iosBundleId: 'com.example.tourmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCab4NAC1L2tEdirexVUpFqOhQM3nyr5ag',
    appId: '1:1042575440295:ios:a4293e7effdcd4d3e8de82',
    messagingSenderId: '1042575440295',
    projectId: 'rafe-3a961',
    databaseURL: 'https://rafe-3a961-default-rtdb.firebaseio.com',
    storageBucket: 'rafe-3a961.firebasestorage.app',
    iosBundleId: 'com.example.tourmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQxdljxL7NyGmSXUrnZLv4hl_kJoLV9ok',
    appId: '1:1042575440295:web:c5fcf07eff124a35e8de82',
    messagingSenderId: '1042575440295',
    projectId: 'rafe-3a961',
    authDomain: 'rafe-3a961.firebaseapp.com',
    databaseURL: 'https://rafe-3a961-default-rtdb.firebaseio.com',
    storageBucket: 'rafe-3a961.firebasestorage.app',
    measurementId: 'G-FKEXE1813F',
  );
}
